version: '3'

services:
  api:
    build: .
    container_name: stock_prediction_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./monitoring:/app/monitoring
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
